apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: jenkins-agent-prod

commonLabels:
  environment: production

patches:
- target:
    kind: Deployment
    name: .*
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1Gi

configMapGenerator:
- name: jenkins-agent-config
  behavior: merge
  literals:
  - REDIS_URL=redis://redis.jenkins-agent-prod:6379
  - MONGODB_URL=mongodb://mongodb.jenkins-agent-prod:27017
  - LM_STUDIO_URL=http://lm-studio.jenkins-agent-prod:8080