apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-agent-config
  namespace: jenkins-agent
data:
  REDIS_URL: "redis://redis:6379"
  MONGODB_URL: "mongodb://mongodb:27017"
  LM_STUDIO_URL: "http://lm-studio:8080"
  PROMETHEUS_PORT: "9090"
  GRAFANA_PORT: "3000"