apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- redis.yaml
- mongodb.yaml
- agents.yaml
- monitoring.yaml

commonLabels:
  app.kubernetes.io/name: jenkins-agent
  app.kubernetes.io/instance: production
  app.kubernetes.io/part-of: jenkins

configMapGenerator:
- name: prometheus-config
  files:
  - prometheus.yml

images:
- name: jenkins-agent-webhook
  newName: jenkins-agent-webhook
  newTag: latest
- name: jenkins-agent-notifier
  newName: jenkins-agent-notifier
  newTag: latest
- name: jenkins-agent-agent
  newName: jenkins-agent-agent
  newTag: latest
- name: jenkins-agent-monitor
  newName: jenkins-agent-monitor
  newTag: latest