apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: jenkins-agent-dev

commonLabels:
  environment: development

patches:
- target:
    kind: Deployment
    name: .*
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1

configMapGenerator:
- name: jenkins-agent-config
  behavior: merge
  literals:
  - REDIS_URL=redis://redis.jenkins-agent-dev:6379
  - MONGODB_URL=mongodb://mongodb.jenkins-agent-dev:27017
  - LM_STUDIO_URL=http://lm-studio.jenkins-agent-dev:8080